# To learn more about the skaffold.yaml schema visit
# https://skaffold.dev/docs/references/yaml/
apiVersion: skaffold/v2beta19
kind: Config
build:
  tagPolicy:
    sha256: {}
  # defines where to find the code at build time and where to push the resulting image
  artifacts:
    - image: java-hello-world
      # To learn more about how Jib builds Java containers visit
      # https://github.com/GoogleContainerTools/jib
      jib:
        args:
        - -Dmaven.test.skip=true

# defines the Kubernetes manifests to deploy on each run
# deploy:
#   kubectl:
#     manifests:
#     - ./k8s/base/**.yaml
deploy:
  kustomize:
    paths: 
      - k8s/base
profiles:
# use the cloudbuild profile to build images using Google Cloud Build
- name: cloudbuild
  build:
    googleCloudBuild: {}
# use the dockerfile profile to build images using Docker instead of Jib
- name: dockerfile
  build:
    artifacts:
      - image: java-hello-world
- name: staging
  deploy:
    kustomize:
      paths: 
        - k8s/overlays/staging
- name: prod
  deploy:
    kustomize:
      paths: 
        - k8s/overlays/prod
