apiVersion: v1
kind: Service
metadata:
  name: java-hello-world-ext
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: java-hello-world
  ports:
  - name: http
    port: 80
    targetPort: 8080